### ISSUE TITLE
Accespoint Mode disable

### ISSUE THREAD

**Issue by bobybobybob** [G6EJD/ESP32-Weather-Forecaster#1]
```
int StartWiFi(const char* ssid, const char* password){
  int connAttempts = 0;
  Serial.println("\r\nConnecting to: "+String(ssid));
    WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
```
WiFi.mode(WIFI_STA);  to disable the no need Accespoint

**Comment by G6EJD** [comment]
What is the issue your reporting, you need to provide more specific information as to what is going wrong.

**Comment by bobybobybob** [comment]
In normal operation your code on the esp8266, it activate a accespoint and brodcast a ssid.     with wifi_sta   that useless accespoint mode is off. Safe a little power and not more WLAN Noise in Wifi Area.

**Comment by G6EJD** [comment]
I’ll update it later today

**Comment by bobybobybob** [comment]
A funny feature... broadcast the trends with the SSID :-)

Little Information for Userguide... if someone want to use a BME280 from China, it need +3.3V on SDO Pin to set i2c to 0x77  and it work with Adafruit_BME280.h libary.

**Comment by G6EJD** [comment]
Yes all Adafruit boards use a different I2C address, mainly I suppose and fair enough, to get customers to buy their boards if using their libraries.
